// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a DIRECT (non-pooled) connection — o pooler transacional
    // (PgBouncer) não suporta os advisory locks do `prisma migrate deploy`.
    // Ordem de preferência:
    //   1. DIRECT_URL (config manual, se existir)
    //   2. POSTGRES_URL_NON_POOLING (injetada pela integração Supabase↔Vercel)
    //   3. DATABASE_URL (fallback)
    url:
      process.env["DIRECT_URL"] ??
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"],
  },
});
